import { BelongToCollection } from '../../belong-to-collection.interface';
import { Genre } from '../../genres/genre.interface';
import { ProductionCompanies } from '../../productions/production-companies.interface';
import { ProductionCountries } from '../../productions/production-countries.interface';
import { SpokenLanguage } from '../../spoken-language.interface';
import { Video } from '../../videos/video.interface';
import { Image } from '../../images/image.interface';
import { Similar } from '../../similar/similar.interface';
import { Credits } from '../../credits/credits.interface';
import { OmdbDetails } from '../../omdb/omdb-details.interface';
import { CreatedBy } from '../../created-by/created-by.interface';
import { EpisodeToAir } from '../../episode-to-air/episode-to-air.interface';
import { Network } from '../../networks/network.interface';
import { SeasonList } from '../../season-list/season-list.interface';
import { ExternalIds } from '../../external-ids/external-ids.interface';

export interface MovieDetails {
  adult: boolean;
  backdrop_path: string;
  belongs_to_collection: BelongToCollection;
  budget: number;
  genres: Genre[];
  homepage: string;
  id: number;
  imdb_id: string;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  production_companies: ProductionCompanies[];
  production_countries: ProductionCountries[];
  release_date: string;
  revenue: number;
  runtime: number;
  spoken_languages: SpokenLanguage[];
  status: string;
  tagline: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
  videos: Video;
  images: Image;
  recommendations: Similar;
  credits: Credits;
  omdbDetails: OmdbDetails;

  created_by: CreatedBy[];
  episode_run_time: [];
  first_air_date: string;
  in_production: boolean;
  languages: [];
  last_air_date: string;
  last_episode_to_air: EpisodeToAir;
  name: string;
  next_episode_to_air: EpisodeToAir;
  networks: Network[];
  number_of_episodes: number;
  number_of_seasons: number;
  origin_country: [];
  original_name: string;
  seasons: SeasonList[];
  type: string;
  external_ids: ExternalIds;
}
